// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: UConfirmation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UKassaPaymentConfirmation_ConfirmPayment_FullMethodName = "/ukassaconfirmation.UKassaPaymentConfirmation/ConfirmPayment"
)

// UKassaPaymentConfirmationClient is the client API for UKassaPaymentConfirmation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UKassaPaymentConfirmationClient interface {
	ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type uKassaPaymentConfirmationClient struct {
	cc grpc.ClientConnInterface
}

func NewUKassaPaymentConfirmationClient(cc grpc.ClientConnInterface) UKassaPaymentConfirmationClient {
	return &uKassaPaymentConfirmationClient{cc}
}

func (c *uKassaPaymentConfirmationClient) ConfirmPayment(ctx context.Context, in *ConfirmPaymentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UKassaPaymentConfirmation_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UKassaPaymentConfirmationServer is the server API for UKassaPaymentConfirmation service.
// All implementations must embed UnimplementedUKassaPaymentConfirmationServer
// for forward compatibility.
type UKassaPaymentConfirmationServer interface {
	ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedUKassaPaymentConfirmationServer()
}

// UnimplementedUKassaPaymentConfirmationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUKassaPaymentConfirmationServer struct{}

func (UnimplementedUKassaPaymentConfirmationServer) ConfirmPayment(context.Context, *ConfirmPaymentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedUKassaPaymentConfirmationServer) mustEmbedUnimplementedUKassaPaymentConfirmationServer() {
}
func (UnimplementedUKassaPaymentConfirmationServer) testEmbeddedByValue() {}

// UnsafeUKassaPaymentConfirmationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UKassaPaymentConfirmationServer will
// result in compilation errors.
type UnsafeUKassaPaymentConfirmationServer interface {
	mustEmbedUnimplementedUKassaPaymentConfirmationServer()
}

func RegisterUKassaPaymentConfirmationServer(s grpc.ServiceRegistrar, srv UKassaPaymentConfirmationServer) {
	// If the following call panics, it indicates UnimplementedUKassaPaymentConfirmationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UKassaPaymentConfirmation_ServiceDesc, srv)
}

func _UKassaPaymentConfirmation_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UKassaPaymentConfirmationServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UKassaPaymentConfirmation_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UKassaPaymentConfirmationServer).ConfirmPayment(ctx, req.(*ConfirmPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UKassaPaymentConfirmation_ServiceDesc is the grpc.ServiceDesc for UKassaPaymentConfirmation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UKassaPaymentConfirmation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ukassaconfirmation.UKassaPaymentConfirmation",
	HandlerType: (*UKassaPaymentConfirmationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmPayment",
			Handler:    _UKassaPaymentConfirmation_ConfirmPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UConfirmation.proto",
}
